import PptxGenJS from 'pptxgenjs';
import { PresentationData, SlideLayout, SlideData } from '../types';

// Helper to replicate the deterministic image logic from Slide.tsx
const getImageUrl = (desc: string | undefined, width: number, height: number) => {
  const seed = desc ? desc.split('').reduce((acc, char) => acc + char.charCodeAt(0), 0) : Math.floor(Math.random() * 1000);
  return `https://picsum.photos/seed/${seed}/${width}/${height}`;
};

export const exportToPptx = async (data: PresentationData) => {
  const pres = new PptxGenJS();
  
  // Set Metadata
  pres.title = data.topic;
  pres.subject = "Generated by Gemini GenAI Presentation Maker";
  pres.layout = 'LAYOUT_16x9';

  // Define a master slide for background consistency (Optional, keeping it simple for now)
  // We will map each slide layout to PPTX elements

  data.slides.forEach((slideData: SlideData, index: number) => {
    const slide = pres.addSlide();
    const { title, subtitle, content, layout, imageDescription } = slideData;

    // Common styling
    const titleOpts = { x: 0.5, y: 0.5, w: '90%', fontSize: 32, bold: true, color: '363636', align: 'center' as const };
    const contentColor = '555555';

    switch (layout) {
      case SlideLayout.TITLE:
        // Dark background style for title slide
        slide.background = { color: '312E81' }; // Indigo-900ish
        slide.addText(title, { 
          x: 0.5, y: '40%', w: '90%', 
          fontSize: 44, bold: true, color: 'FFFFFF', align: 'center' 
        });
        if (subtitle) {
          slide.addText(subtitle, { 
            x: 0.5, y: '55%', w: '90%', 
            fontSize: 24, color: 'E0E7FF', align: 'center' 
          });
        }
        break;

      case SlideLayout.CENTERED_TEXT:
        slide.addText(title, { ...titleOpts, y: 0.5 });
        slide.addText(content.join('\n\n'), {
          x: 1, y: 1.5, w: '80%', h: 4,
          fontSize: 18, color: contentColor, align: 'center',
          breakLine: true
        });
        break;

      case SlideLayout.BULLET_POINTS_LEFT:
        // Title top
        slide.addText(title, { x: 0.5, y: 0.5, w: '90%', fontSize: 28, bold: true, color: '363636' });
        // Content Left
        slide.addText(content.map(c => ({ text: c, options: { breakLine: true } })), {
          x: 0.5, y: 1.5, w: '45%', h: 5,
          fontSize: 16, color: contentColor, bullet: true, valign: 'top'
        });
        // Image Right
        slide.addImage({
          path: getImageUrl(imageDescription, 800, 1000),
          x: '53%', y: 1.5, w: '42%', h: 5
        });
        break;

      case SlideLayout.BULLET_POINTS_RIGHT:
        // Title top
        slide.addText(title, { x: 0.5, y: 0.5, w: '90%', fontSize: 28, bold: true, color: '363636' });
        // Image Left
        slide.addImage({
          path: getImageUrl(imageDescription, 800, 1000),
          x: 0.5, y: 1.5, w: '42%', h: 5
        });
        // Content Right
        slide.addText(content.map(c => ({ text: c, options: { breakLine: true } })), {
          x: '53%', y: 1.5, w: '45%', h: 5,
          fontSize: 16, color: contentColor, bullet: true, valign: 'top'
        });
        break;

      case SlideLayout.IMAGE_FEATURE:
        // Full background image with overlay box
        slide.addImage({
          path: getImageUrl(imageDescription, 1200, 800),
          x: 0, y: 0, w: '100%', h: '100%'
        });
        // Semi-transparent box for text
        slide.addShape(pres.ShapeType.rect, { 
          x: 0, y: '65%', w: '100%', h: '35%', 
          fill: { color: '000000', transparency: 30 } 
        });
        slide.addText(title, { 
          x: 0.5, y: '70%', w: '90%', 
          fontSize: 32, bold: true, color: 'FFFFFF' 
        });
        slide.addText(content.join(' '), { 
          x: 0.5, y: '82%', w: '90%', h: 1, 
          fontSize: 16, color: 'F3F4F6' 
        });
        break;

      default:
        // Fallback generic
        slide.addText(title, { x: 0.5, y: 0.5, w: '90%', fontSize: 24, bold: true });
        slide.addText(content.join('\n'), { x: 0.5, y: 1.5, w: '90%', fontSize: 14, bullet: true });
        break;
    }

    // Add Footer
    slide.addText(`GenAI Slides - ${index + 1}`, {
      x: '90%', y: '92%', w: '10%', h: 0.3,
      fontSize: 10, color: 'AAAAAA', align: 'right'
    });
  });

  await pres.writeFile({ fileName: `${data.topic.replace(/[^a-z0-9]/gi, '_').substring(0, 20)}_Presentation.pptx` });
};